# Generated by Django 5.2.7 on 2025-10-21 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='唯一的验证令牌', unique=True, verbose_name='验证令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(help_text='令牌过期时间', verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='令牌是否已被使用', verbose_name='已使用')),
                ('user', models.ForeignKey(help_text='验证令牌所属的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_em_token_21db79_idx'), models.Index(fields=['user', '-created_at'], name='accounts_em_user_id_1b4ad5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='11位手机号码', max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, help_text='个人简介，最多500字符', max_length=500, verbose_name='个人简介')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, verbose_name='性别')),
                ('email_verified', models.BooleanField(default=False, help_text='邮箱是否已通过验证', verbose_name='邮箱已验证')),
                ('phone_verified', models.BooleanField(default=False, help_text='手机号是否已通过验证', verbose_name='手机已验证')),
                ('login_count', models.IntegerField(default=0, help_text='用户累计登录次数', verbose_name='登录次数')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='用户最后一次登录的IP地址', null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间', verbose_name='更新时间')),
                ('user', models.OneToOneField(help_text='关联到Django内置的User模型', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='accounts_us_phone_27e73a_idx'), models.Index(fields=['-created_at'], name='accounts_us_created_a2ea9d_idx')],
            },
        ),
    ]
