# Generated by Django 5.2.7 on 2025-10-21 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：OpenAI配置、本地模型配置', max_length=100, unique=True, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('local', '本地模型'), ('other', '其他')], default='openai', max_length=20, verbose_name='提供商')),
                ('model_name', models.CharField(default='gpt-3.5-turbo', help_text='例如：gpt-3.5-turbo, gpt-4, claude-3-sonnet', max_length=100, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, help_text='LLM服务的API密钥', max_length=200, verbose_name='API密钥')),
                ('api_base', models.CharField(blank=True, help_text='可选，用于自定义API端点', max_length=200, verbose_name='API基础URL')),
                ('is_active', models.BooleanField(default=True, help_text='只有启用的配置才会被使用', verbose_name='是否启用')),
                ('max_tokens', models.IntegerField(default=2000, help_text='单次对话的最大token数量', verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, help_text='0-1之间，越高越随机，越低越确定', verbose_name='温度参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM配置',
                'verbose_name_plural': 'LLM配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手')], help_text='消息的发送者角色', max_length=20, verbose_name='角色')),
                ('content', models.TextField(help_text='对话的具体内容', verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session_id', models.CharField(default='default', help_text='用于区分不同的对话会话', max_length=100, verbose_name='会话ID')),
                ('user', models.ForeignKey(help_text='消息所属的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['-created_at'],
            },
        ),
    ]
